---
title: Two Moulins
logo: 
description: Le récit des aventures sportives des deux Moulins, Félix & Philippe,
  suivez-les à vélos ou dans d'autres activités.
baseurl: ''
url: https://lobwick.github.io/
author-name: Two Moulins
hero:
  image: '/assets/images/twomoulins.jpg'
  title: Two Moulins
  description: 
social:
- icon: ion-logo-twitter
  link: https://twitter.com/Lobwick
- icon: ion-logo-facebook
  link: https://www.facebook.com/twomoulins
- icon: ion-logo-instagram
  link: https://www.instagram.com/lobwick/
contact:
  email: lobwick@hotmail.fr
  description: Besoin de nous envoyer un petit message, envie de venir rouler avec nous ou tout simplement de dire bonjour ? 
disqus-identifier: twomoulins
mailchimp: false
mailchimp-title: Les nouvelles aventures
mailchimp-text: Pour être au courant des nouvelles aventures des TwoMoulins n'hésitez pas à vous inscire à la newsletter.
mailchimp-identifier: 
markdown: kramdown
permalink: "/:title"
plugins:
- ''
- jekyll-paginate
- jekyll-sitemap
- jekyll/tagging
paginate: "8"
paginate_path: "/page/:num"
defaults:
- scope:
    path: _pages
  values:
    permalink: "/:basename:output_ext"
include:
- _pages
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: "/:title"
sass:
  sass_dir: _sass
  style: compressed
