---
title: Two Moulins
logo: 
description: Le récit des aventures sportives des deux Moulins, Félix & Philippe,
  suivez-les à vélos ou dans d'autres activités.
baseurl: ''
url: https://lobwick.github.io/
author-name: Two Moulins
hero:
  image: '/images/twomoulins.jpg'
  title: Two Moulins
  description: 
social:
- icon: ion-logo-twitter
  link: https://twitter.com
- icon: ion-logo-facebook
  link: https://facebook.com
- icon: ion-logo-dribbble
  link: https://dribbble.com
- icon: ion-logo-instagram
  link: https://instagram.com
- icon: ion-logo-github
  link: https://github.com
- icon: ion-logo-vimeo
  link: https://vimeo.com/
contact:
  email: lobwick@hotmail.fr
  description: Sanara comes with a built-in contact form, that you can use with Formspree
    service to handle up to 50 submissions per month for free. You could also easily
    switch to another contact form service if you want.
disqus-identifier: anvodstudio-demo
mailchimp: false
mailchimp-title: Get Interesting News
mailchimp-text: Subscribe to our newsletter and we’ll send you the emails of latest
  posts.
mailchimp-identifier: 
markdown: kramdown
permalink: "/:title"
plugins:
- ''
- jekyll-paginate
- jekyll-sitemap
- jekyll/tagging
paginate: "8"
paginate_path: "/page/:num"
defaults:
- scope:
    path: _pages
  values:
    permalink: "/:basename:output_ext"
include:
- _pages
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: "/:title"
sass:
  sass_dir: _sass
  style: compressed
