name: Build and Sonar scan

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: checkout
        with:
          fetch-depth: 0
      - uses: actions/jekyll-build-pages@v1
        id: build 


      - name: Cache HTMLProofer
        id: cache-htmlproofer
        uses: actions/cache@v2
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer-${{ hashFiles('_site/**.html') }}
          restore-keys: |
            ${{ runner.os }}-htmlproofer-
            ${{ runner.os }}-htmlproofer
     